
--  DDL for Table CTHD
--------------------------------------------------------

  CREATE TABLE CTHD
  (	
    "MAHD" CHAR(6 BYTE), 
	  "LOAIHD" VARCHAR2(20 BYTE), 
	  "SL" NUMBER(*,0), 
	  "DONGIA" NUMBER(*,0), 
	  "THANHTIEN" NUMBER(*,0)
  ) 
  SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CTHOPDONG
--------------------------------------------------------

  CREATE TABLE CTHOPDONG
  (	
    "MHD" CHAR(6 BYTE), 
	  "MAKT" CHAR(6 BYTE)
  ) 
  SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CTPDV
--------------------------------------------------------

  CREATE TABLE CTPDV
  (	
    "MADV" CHAR(6 BYTE), 
	  "MPDV" CHAR(6 BYTE), 
	  "TINHTRANG" VARCHAR2(20 BYTE)
  ) 
  SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DICHVU
--------------------------------------------------------

  CREATE TABLE DICHVU
  (	
    "MADV" CHAR(6 BYTE), 
	  "TENDICHVU" VARCHAR2(40 BYTE)
  ) 
  SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HOADON
--------------------------------------------------------

  CREATE TABLE HOADON
  (	
    "MAHD" CHAR(6 BYTE), 
    "MAP" CHAR(4 BYTE), 
	  "THANG" NUMBER(*,0), 
    "NAM" NUMBER(*,0), 
    "TONGTIEN" NUMBER(*,0), 
    "TRANGTHAI" VARCHAR2(30 BYTE), 
    "CONNO" NUMBER(*,0)
  ) 
  SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HOPDONG
--------------------------------------------------------

  CREATE TABLE HOPDONG
  (	
    "MHD" CHAR(6 BYTE), 
    "NGAYBATDAU" DATE, 
    "NGAYKETTHUC" DATE, 
    "MADD" CHAR(6 BYTE), 
    "MAP" CHAR(4 BYTE), 
    "GIATHUE" NUMBER(*,0), 
    "TIENCOC" NUMBER, 
    "TINHTRANG" VARCHAR2(20 BYTE)
  ) 
  SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KHACHNGANHAN
--------------------------------------------------------

  CREATE TABLE KHACHNGANHAN 
  (	
    "MAKT" CHAR(6 BYTE), 
    "HOTEN" VARCHAR2(60 BYTE), 
    "GIOITINH" VARCHAR2(10 BYTE), 
    "NGAYSINH" DATE, 
    "SDT" VARCHAR2(20 BYTE), 
    "CCCD" VARCHAR2(20 BYTE), 
    "EMAIL" VARCHAR2(60 BYTE), 
    "MADD" CHAR(6 BYTE), 
    "TRANGTHAI" VARCHAR2(20 BYTE), 
    "NGAYBATDAU" DATE, 
    "NGAYKETTHUC" DATE
  ) 
  SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KHACHTHUE
--------------------------------------------------------

  CREATE TABLE KHACHTHUE 
  (	
    "MAKT" CHAR(6 BYTE), 
    "HOTEN" VARCHAR2(60 BYTE), 
    "GIOITINH" VARCHAR2(10 BYTE), 
    "NGAYSINH" DATE, 
    "SDT" VARCHAR2(20 BYTE) DEFAULT (null), 
    "CCCD" VARCHAR2(20 BYTE), 
    "EMAIL" VARCHAR2(60 BYTE), 
    "NGAYBATDAU" DATE, 
    "NGAYKETTHUC" DATE
  ) 
  SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PHIEUDICHVU
--------------------------------------------------------

  CREATE TABLE PHIEUDICHVU
  (	
    "MPDV" CHAR(6 BYTE), 
    "MAP" CHAR(4 BYTE), 
    "SOLUONGDV" NUMBER(*,0), 
    "NGAYDIEN" DATE
  ) 
  SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PHONG
--------------------------------------------------------

  CREATE TABLE PHONG
  (	
    "MAP" CHAR(4 BYTE), 
    "TENPG" VARCHAR2(10 BYTE), 
    "LOAI" VARCHAR2(20 BYTE), 
    "SONGUOI" NUMBER(*,0), 
    "DIENTICH" NUMBER(*,0), 
    "TRANGTHAI" VARCHAR2(20 BYTE), 
    "GIA" NUMBER(*,0)
  ) 
  SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAIKHOAN
--------------------------------------------------------

  CREATE TABLE TAIKHOAN 
  (	
    "MATK" CHAR(6 BYTE), 
    "MAKT" CHAR(6 BYTE), 
    "TENTAIKHOAN" VARCHAR2(40 BYTE), 
    "MATKHAU" VARCHAR2(40 BYTE), 
    "VAITRO" VARCHAR2(20 BYTE)
  ) 
  SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


REM INSERTING into CTHD
SET DEFINE OFF;
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0025','Phòng','1','7800000','7800000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0026','Phòng','1','3000000','3000000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0001','Phòng','1','3000000','3000000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0001','Điện','200','5000','1000000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0001','Nước','20','10000','200000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0002','Phòng','1','3000000','3000000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0002','Điện','220','5000','1100000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0002','Nước','22','10000','220000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0003','Phòng','1','3000000','3000000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0003','Điện','230','5000','1150000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0003','Nước','23','10000','230000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0005','Phòng','1','3200000','3200000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0005','Điện','250','5000','1250000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0005','Nước','25','10000','250000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0006','Phòng','1','3200000','3200000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0006','Điện','260','5000','1300000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0006','Nước','26','10000','260000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0007','Phòng','1','3200000','3200000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0007','Điện','270','5000','1350000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0007','Nước','27','10000','270000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0008','Phòng','1','3200000','3200000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0008','Điện','280','5000','1400000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0008','Nước','28','10000','280000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0009','Phòng','1','3300000','3300000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0009','Điện','250','5000','1250000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0009','Nước','25','10000','250000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0010','Phòng','1','3300000','3300000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0010','Điện','260','5000','1300000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0010','Nước','26','10000','260000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0011','Phòng','1','3300000','3300000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0011','Điện','270','5000','1350000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0011','Nước','27','10000','270000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0013','Phòng','1','3100000','3100000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0013','Điện','200','5000','1000000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0013','Nước','20','10000','200000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0014','Phòng','1','3100000','3100000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0014','Điện','210','5000','1050000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0014','Nước','21','10000','210000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0015','Phòng','1','3100000','3100000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0015','Điện','220','5000','1100000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0015','Nước','22','10000','220000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0016','Phòng','1','3100000','3100000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0016','Điện','230','5000','1150000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0016','Nước','23','10000','230000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0017','Phòng','1','3500000','3500000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0017','Điện','200','5000','1000000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0017','Nước','20','10000','200000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0018','Phòng','1','3500000','3500000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0018','Điện','210','5000','1050000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0018','Nước','21','10000','210000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0019','Phòng','1','3500000','3500000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0019','Điện','220','5000','1100000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0019','Nước','22','10000','220000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0021','Phòng','1','3200000','3200000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0021','Điện','190','5000','950000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0021','Nước','19','10000','190000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0022','Phòng','1','3200000','3200000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0022','Điện','200','5000','1000000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0022','Nước','20','10000','200000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0023','Phòng','1','3200000','3200000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0023','Điện','210','5000','1050000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0023','Nước','21','10000','210000');
Insert into CTHD (MAHD,LOAIHD,SL,DONGIA,THANHTIEN) values ('HD0025','Điện','1','900000','900000');

REM INSERTING into CTHOPDONG
SET DEFINE OFF;
Insert into CTHOPDONG (MHD,MAKT) values ('HD002 ','KT0002');
Insert into CTHOPDONG (MHD,MAKT) values ('HD002 ','KT0004');
Insert into CTHOPDONG (MHD,MAKT) values ('HD003 ','KT0005');
Insert into CTHOPDONG (MHD,MAKT) values ('HD004 ','KT0006');
Insert into CTHOPDONG (MHD,MAKT) values ('HD005 ','KT0007');
Insert into CTHOPDONG (MHD,MAKT) values ('HD005 ','KT0008');
Insert into CTHOPDONG (MHD,MAKT) values ('HD010 ','KT0004');
Insert into CTHOPDONG (MHD,MAKT) values ('HD012 ','KT0011');
Insert into CTHOPDONG (MHD,MAKT) values ('HD013 ','KT0012');
Insert into CTHOPDONG (MHD,MAKT) values ('HD013 ','KT0013');
Insert into CTHOPDONG (MHD,MAKT) values ('HD016 ','KT0014');
Insert into CTHOPDONG (MHD,MAKT) values ('HD016 ','KT0015');
Insert into CTHOPDONG (MHD,MAKT) values ('HD018 ','KT0015');
Insert into CTHOPDONG (MHD,MAKT) values ('HD019 ','KT0017');
Insert into CTHOPDONG (MHD,MAKT) values ('HD020 ','KT0016');
Insert into CTHOPDONG (MHD,MAKT) values ('HD021 ','KT0014');
Insert into CTHOPDONG (MHD,MAKT) values ('HD022 ','KT0014');
Insert into CTHOPDONG (MHD,MAKT) values ('HD023 ','KT0014');
Insert into CTHOPDONG (MHD,MAKT) values ('HD024 ','KT0012');

REM INSERTING into CTPDV
SET DEFINE OFF;
Insert into CTPDV (MADV,MPDV,TINHTRANG) values ('DV003 ','PDV002','Chưa hoàn thành');
Insert into CTPDV (MADV,MPDV,TINHTRANG) values ('DV001 ','PDV004','Chưa hoàn thành');
Insert into CTPDV (MADV,MPDV,TINHTRANG) values ('DV002 ','PDV004','Chưa hoàn thành');
Insert into CTPDV (MADV,MPDV,TINHTRANG) values ('DV003 ','PDV004','Chưa hoàn thành');

REM INSERTING into DICHVU
SET DEFINE OFF;
Insert into DICHVU (MADV,TENDICHVU) values ('DV006 ','Ghế');
Insert into DICHVU (MADV,TENDICHVU) values ('DV001 ','Bàn');
Insert into DICHVU (MADV,TENDICHVU) values ('DV002 ','Cửa');
Insert into DICHVU (MADV,TENDICHVU) values ('DV003 ','Ống Nước');
Insert into DICHVU (MADV,TENDICHVU) values ('DV004 ','Toilet');
Insert into DICHVU (MADV,TENDICHVU) values ('DV005 ','��n');
Insert into DICHVU (MADV,TENDICHVU) values ('DV007 ','Ly');

REM INSERTING into HOADON
SET DEFINE OFF;
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0025','P007','8','2024','8700000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0026','P001','5','2024','3000000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0027','P011','5','2024','0','Chưa thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0001','P001','1','2024','3200000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0002','P001','2','2024','4320000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0003','P001','3','2024','4380000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0005','P002','1','2024','4700000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0006','P002','2','2024','4760000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0007','P002','3','2024','4820000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0008','P002','4','2024','4880000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0009','P003','1','2024','4800000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0010','P003','2','2024','4860000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0011','P003','3','2024','4920000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0013','P004','1','2024','4300000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0014','P004','2','2024','4360000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0015','P004','3','2024','4420000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0016','P004','4','2024','4480000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0017','P011','1','2024','4700000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0018','P011','2','2024','4760000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0019','P011','3','2024','4820000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0021','P012','1','2024','4340000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0022','P012','2','2024','4400000','Đã thanh toán','0');
Insert into HOADON (MAHD,MAP,THANG,NAM,TONGTIEN,TRANGTHAI,CONNO) values ('HD0023','P012','3','2024','4460000','Đã thanh toán','0');

REM INSERTING into HOPDONG
SET DEFINE OFF;
Insert into HOPDONG (MHD,NGAYBATDAU,NGAYKETTHUC,MADD,MAP,GIATHUE,TIENCOC,TINHTRANG) values ('HD016 ',to_date('03-06-2024','DD-MM-RRRR'),to_date('03-06-2025','DD-MM-RRRR'),'KT0014','P018','3300000','3000000','Hết hiệu lực');
Insert into HOPDONG (MHD,NGAYBATDAU,NGAYKETTHUC,MADD,MAP,GIATHUE,TIENCOC,TINHTRANG) values ('HD021 ',to_date('02-06-2025','DD-MM-RRRR'),to_date('13-06-2026','DD-MM-RRRR'),'KT0014','P015','3400000','4000000','Hết hiệu lực');
Insert into HOPDONG (MHD,NGAYBATDAU,NGAYKETTHUC,MADD,MAP,GIATHUE,TIENCOC,TINHTRANG) values ('HD019 ',to_date('31-05-2024','DD-MM-RRRR'),to_date('01-05-2025','DD-MM-RRRR'),'KT0017','P008','3300000','3453453','Hết hiệu lực');
Insert into HOPDONG (MHD,NGAYBATDAU,NGAYKETTHUC,MADD,MAP,GIATHUE,TIENCOC,TINHTRANG) values ('HD012 ',to_date('01-06-2024','DD-MM-RRRR'),to_date('01-06-2025','DD-MM-RRRR'),'KT0011','P007','3200000','3000000','Hiệu lực');
Insert into HOPDONG (MHD,NGAYBATDAU,NGAYKETTHUC,MADD,MAP,GIATHUE,TIENCOC,TINHTRANG) values ('HD023 ',to_date('08-04-2025','DD-MM-RRRR'),to_date('07-06-2026','DD-MM-RRRR'),'KT0014','P001','3000000','453464','Hiệu lực');
Insert into HOPDONG (MHD,NGAYBATDAU,NGAYKETTHUC,MADD,MAP,GIATHUE,TIENCOC,TINHTRANG) values ('HD010 ',to_date('01-06-2024','DD-MM-RRRR'),to_date('01-06-2025','DD-MM-RRRR'),'KT0004','P020','3400000','5000000','Hết hiệu lực');
Insert into HOPDONG (MHD,NGAYBATDAU,NGAYKETTHUC,MADD,MAP,GIATHUE,TIENCOC,TINHTRANG) values ('HD018 ',to_date('31-05-2024','DD-MM-RRRR'),to_date('30-04-2025','DD-MM-RRRR'),'KT0015','P019','3100000','789789','Hiệu lực');
Insert into HOPDONG (MHD,NGAYBATDAU,NGAYKETTHUC,MADD,MAP,GIATHUE,TIENCOC,TINHTRANG) values ('HD024 ',to_date('01-06-2025','DD-MM-RRRR'),to_date('20-06-2026','DD-MM-RRRR'),'KT0012','P016','3500000','4000000','Hiệu lực');
Insert into HOPDONG (MHD,NGAYBATDAU,NGAYKETTHUC,MADD,MAP,GIATHUE,TIENCOC,TINHTRANG) values ('HD002 ',to_date('01-01-2024','DD-MM-RRRR'),to_date('01-01-2025','DD-MM-RRRR'),'KT0002','P002','3200000','4500000','Hiệu lực');
Insert into HOPDONG (MHD,NGAYBATDAU,NGAYKETTHUC,MADD,MAP,GIATHUE,TIENCOC,TINHTRANG) values ('HD003 ',to_date('01-12-2023','DD-MM-RRRR'),to_date('01-12-2024','DD-MM-RRRR'),'KT0005','P003','3300000','4800000','Hiệu lực');
Insert into HOPDONG (MHD,NGAYBATDAU,NGAYKETTHUC,MADD,MAP,GIATHUE,TIENCOC,TINHTRANG) values ('HD004 ',to_date('01-03-2024','DD-MM-RRRR'),to_date('01-03-2025','DD-MM-RRRR'),'KT0006','P004','3500000','5000000','Hiệu lực');
Insert into HOPDONG (MHD,NGAYBATDAU,NGAYKETTHUC,MADD,MAP,GIATHUE,TIENCOC,TINHTRANG) values ('HD005 ',to_date('01-03-2024','DD-MM-RRRR'),to_date('01-03-2025','DD-MM-RRRR'),'KT0007','P011','3100000','4000000','Hết hiệu lực');
Insert into HOPDONG (MHD,NGAYBATDAU,NGAYKETTHUC,MADD,MAP,GIATHUE,TIENCOC,TINHTRANG) values ('HD022 ',to_date('02-04-2024','DD-MM-RRRR'),to_date('08-04-2025','DD-MM-RRRR'),'KT0014','P001','3000000','453464','Hết hiệu lực');
Insert into HOPDONG (MHD,NGAYBATDAU,NGAYKETTHUC,MADD,MAP,GIATHUE,TIENCOC,TINHTRANG) values ('HD013 ',to_date('01-06-2024','DD-MM-RRRR'),to_date('01-06-2025','DD-MM-RRRR'),'KT0012','P016','3500000','4000000','Hết hiệu lực');
Insert into HOPDONG (MHD,NGAYBATDAU,NGAYKETTHUC,MADD,MAP,GIATHUE,TIENCOC,TINHTRANG) values ('HD020 ',to_date('30-05-2024','DD-MM-RRRR'),to_date('13-06-2025','DD-MM-RRRR'),'KT0016','P014','3100000','987654','Hiệu lực');

REM INSERTING into KHACHNGANHAN
SET DEFINE OFF;
Insert into KHACHNGANHAN (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,MADD,TRANGTHAI,NGAYBATDAU,NGAYKETTHUC) values ('KNH007','hello','Nữ',to_date('29-05-2019','DD-MM-RRRR'),'+8422222222222','765444979989',null,'KT0007','Đã duyệt',to_date('02-06-2024','DD-MM-RRRR'),to_date('13-06-2024','DD-MM-RRRR'));
Insert into KHACHNGANHAN (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,MADD,TRANGTHAI,NGAYBATDAU,NGAYKETTHUC) values ('KNH008','lolila','Nam',to_date('25-06-2020','DD-MM-RRRR'),'+849089574576',null,null,'KT0007','Đã duyệt',to_date('08-06-2024','DD-MM-RRRR'),to_date('28-06-2024','DD-MM-RRRR'));
Insert into KHACHNGANHAN (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,MADD,TRANGTHAI,NGAYBATDAU,NGAYKETTHUC) values ('KNH002','Trần Văn B','Nam',to_date('02-02-1994','DD-MM-RRRR'),'+84123456792','234567890','tranvanb@example.com','KT0002','Đã duyệt',to_date('02-01-2024','DD-MM-RRRR'),to_date('31-01-2024','DD-MM-RRRR'));
Insert into KHACHNGANHAN (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,MADD,TRANGTHAI,NGAYBATDAU,NGAYKETTHUC) values ('KNH004','Lê Thị D','Nữ',to_date('04-04-1992','DD-MM-RRRR'),'+84123456794','456789012','lethid@example.com','KT0004','Chờ duyệt',to_date('04-01-2024','DD-MM-RRRR'),to_date('31-01-2024','DD-MM-RRRR'));
Insert into KHACHNGANHAN (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,MADD,TRANGTHAI,NGAYBATDAU,NGAYKETTHUC) values ('KNH005','Nguyễn Văn E','Nam',to_date('05-05-1991','DD-MM-RRRR'),'+84123456795','567890123','nguyenvane@example.com','KT0005','Đã duyệt',to_date('05-01-2024','DD-MM-RRRR'),to_date('31-01-2024','DD-MM-RRRR'));
Insert into KHACHNGANHAN (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,MADD,TRANGTHAI,NGAYBATDAU,NGAYKETTHUC) values ('KNH006','Nguyễn Thị J','Nữ',to_date('04-06-2016','DD-MM-RRRR'),'+8445345346','0675674563456','J@gm.com','KT0002','Đã duyệt',to_date('07-06-2024','DD-MM-RRRR'),to_date('14-06-2024','DD-MM-RRRR'));

REM INSERTING into KHACHTHUE
SET DEFINE OFF;
Insert into KHACHTHUE (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,NGAYBATDAU,NGAYKETTHUC) values ('KT0013','lele','Nam',to_date('06-06-2015','DD-MM-RRRR'),'+84678544246','067457456346','l@gm.com',to_date('01-06-2024','DD-MM-RRRR'),to_date('01-06-2025','DD-MM-RRRR'));
Insert into KHACHTHUE (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,NGAYBATDAU,NGAYKETTHUC) values ('KT0014','lala','Nam',to_date('31-05-2008','DD-MM-RRRR'),'+84345784375','0823489234','lala@gm.com',to_date('02-04-2024','DD-MM-RRRR'),to_date('07-06-2026','DD-MM-RRRR'));
Insert into KHACHTHUE (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,NGAYBATDAU,NGAYKETTHUC) values ('KT0016','koko','Nam',to_date('10-06-2023','DD-MM-RRRR'),'+84999999999','6643227888','koko@gm.com',to_date('30-05-2024','DD-MM-RRRR'),to_date('13-06-2025','DD-MM-RRRR'));
Insert into KHACHTHUE (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,NGAYBATDAU,NGAYKETTHUC) values ('KT0011','nana','Nam',to_date('10-06-2017','DD-MM-RRRR'),null,null,null,to_date('01-06-2024','DD-MM-RRRR'),to_date('01-06-2025','DD-MM-RRRR'));
Insert into KHACHTHUE (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,NGAYBATDAU,NGAYKETTHUC) values ('KT0012','lulu','Nữ',to_date('15-06-2013','DD-MM-RRRR'),'+84534543565','043456756756',null,to_date('01-06-2024','DD-MM-RRRR'),to_date('20-06-2026','DD-MM-RRRR'));
Insert into KHACHTHUE (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,NGAYBATDAU,NGAYKETTHUC) values ('KT0015','lili','Nữ',to_date('31-05-2008','DD-MM-RRRR'),'+84432343453','0832493849','lili@gm.com',to_date('31-05-2024','DD-MM-RRRR'),to_date('30-04-2025','DD-MM-RRRR'));
Insert into KHACHTHUE (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,NGAYBATDAU,NGAYKETTHUC) values ('KT0002','Nguyễn Mỹ Ngân','Nữ',to_date('10-02-2006','DD-MM-RRRR'),'+84123456764','2345678904','myngannguyen174@gmail.com',to_date('04-06-2022','DD-MM-RRRR'),to_date('01-01-2025','DD-MM-RRRR'));
Insert into KHACHTHUE (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,NGAYBATDAU,NGAYKETTHUC) values ('KT0004','Lê Thị D','Nữ',to_date('04-04-2003','DD-MM-RRRR'),'+84123456784','456789012879','lethid@example.com',to_date('04-01-2024','DD-MM-RRRR'),to_date('01-01-2025','DD-MM-RRRR'));
Insert into KHACHTHUE (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,NGAYBATDAU,NGAYKETTHUC) values ('KT0005','Nguyễn Văn E','Nam',to_date('05-05-2004','DD-MM-RRRR'),'+84123456785','567890123','nguyenvane@example.com',to_date('05-01-2024','DD-MM-RRRR'),to_date('31-12-2024','DD-MM-RRRR'));
Insert into KHACHTHUE (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,NGAYBATDAU,NGAYKETTHUC) values ('KT0006','Trần Văn F','Nam',to_date('06-06-2003','DD-MM-RRRR'),'+84123456786','678901234','tranvanf@example.com',to_date('01-01-2024','DD-MM-RRRR'),to_date('31-12-2024','DD-MM-RRRR'));
Insert into KHACHTHUE (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,NGAYBATDAU,NGAYKETTHUC) values ('KT0007','Lê Thị G','Nữ',to_date('07-07-1996','DD-MM-RRRR'),'+84123456787','789012345','lethig@example.com',to_date('02-01-2024','DD-MM-RRRR'),to_date('31-12-2024','DD-MM-RRRR'));
Insert into KHACHTHUE (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,NGAYBATDAU,NGAYKETTHUC) values ('KT0008','Nguyễn Văn H','Nam',to_date('08-08-1992','DD-MM-RRRR'),'+84123456788','890123456','nguyenvanh@example.com',to_date('03-01-2024','DD-MM-RRRR'),to_date('31-12-2024','DD-MM-RRRR'));
Insert into KHACHTHUE (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,NGAYBATDAU,NGAYKETTHUC) values ('KT0010','Trần Văn K','Nam',to_date('10-10-1994','DD-MM-RRRR'),'+84123456790','012345678','tranvank@example.com',to_date('05-01-2024','DD-MM-RRRR'),to_date('02-06-2024','DD-MM-RRRR'));
Insert into KHACHTHUE (MAKT,HOTEN,GIOITINH,NGAYSINH,SDT,CCCD,EMAIL,NGAYBATDAU,NGAYKETTHUC) values ('KT0017','keke','Nam',to_date('13-06-2015','DD-MM-RRRR'),'+84890775432','0865746568','k@gm.com',to_date('31-05-2024','DD-MM-RRRR'),to_date('02-06-2024','DD-MM-RRRR'));

REM INSERTING into PHIEUDICHVU
SET DEFINE OFF;
Insert into PHIEUDICHVU (MPDV,MAP,SOLUONGDV,NGAYDIEN) values ('PDV002','P002','1',to_date('07-05-2024','DD-MM-RRRR'));
Insert into PHIEUDICHVU (MPDV,MAP,SOLUONGDV,NGAYDIEN) values ('PDV004','P018','3',to_date('02-06-2024','DD-MM-RRRR'));

REM INSERTING into PHONG
SET DEFINE OFF;
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P001','P101','Sinh viên','1','25','Đã cho thuê','3000000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P002','P102','Sinh viên','2','20','Đã cho thuê','3200000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P003','P103','Sinh viên','1','30','Đã cho thuê','3300000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P004','P104','Sinh viên','1','22','Đã cho thuê','3100000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P005','P105','Sinh viên','0','18','Còn Trống','3500000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P006','P106','Sinh viên','0','25','Còn Trống','3500000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P007','P107','Sinh viên','1','20','Đã cho thuê','3200000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P008','P108','Sinh viên','0','30','Còn Trống','3300000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P009','P109','Sinh viên','0','22','Còn Trống','3100000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P010','P110','Sinh viên','0','18','Còn Trống','3400000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P011','P201','Gia đình','0','25','Còn Trống','3600000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P012','P202','Gia đình','0','20','Còn Trống','3200000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P013','P203','Gia đình','0','30','Còn Trống','3300000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P014','P204','Gia đình','1','22','Đã cho thuê','3100000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P015','P205','Gia đình','0','18','Còn Trống','3400000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P016','P206','Gia đình','1','25','Đã cho thuê','3500000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P017','P207','Gia đình','0','20','Còn Trống','3200000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P018','P208','Gia đình','0','30','Còn Trống','3300000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P019','P209','Gia đình','1','22','Đã cho thuê','3100000');
Insert into PHONG (MAP,TENPG,LOAI,SONGUOI,DIENTICH,TRANGTHAI,GIA) values ('P020','P210','Gia đình','0','18','Còn Trống','3400000');

REM INSERTING into TAIKHOAN
SET DEFINE OFF;
Insert into TAIKHOAN (MATK,MAKT,TENTAIKHOAN,MATKHAU,VAITRO) values ('TK0012','KT0013','l@gm.com','123456','Khách thuê');
Insert into TAIKHOAN (MATK,MAKT,TENTAIKHOAN,MATKHAU,VAITRO) values ('TK0002','KT0002','myngannguyen174@gmail.com','12','Khách thuê');
Insert into TAIKHOAN (MATK,MAKT,TENTAIKHOAN,MATKHAU,VAITRO) values ('TK0013','KT0014','lala@gm.com','123456','Khách thuê');
Insert into TAIKHOAN (MATK,MAKT,TENTAIKHOAN,MATKHAU,VAITRO) values ('TK0004','KT0004','lethid@example.com','123456','Khách thuê');
Insert into TAIKHOAN (MATK,MAKT,TENTAIKHOAN,MATKHAU,VAITRO) values ('TK0005','KT0005','nguyenvane@example.com','123456','Khách thuê');
Insert into TAIKHOAN (MATK,MAKT,TENTAIKHOAN,MATKHAU,VAITRO) values ('TK0006','KT0006','tranvanf@example.com','123456','Khách thuê');
Insert into TAIKHOAN (MATK,MAKT,TENTAIKHOAN,MATKHAU,VAITRO) values ('TK0007','KT0007','lethig@example.com','123456','Khách thuê');
Insert into TAIKHOAN (MATK,MAKT,TENTAIKHOAN,MATKHAU,VAITRO) values ('TK0008','KT0008','nguyenvanh@example.com','123456','Khách thuê');
Insert into TAIKHOAN (MATK,MAKT,TENTAIKHOAN,MATKHAU,VAITRO) values ('TK0010','KT0010','ranvank@example.com','123456','Khách thuê');
Insert into TAIKHOAN (MATK,MAKT,TENTAIKHOAN,MATKHAU,VAITRO) values ('TK0011',null,'u','1','Chủ trọ');
Insert into TAIKHOAN (MATK,MAKT,TENTAIKHOAN,MATKHAU,VAITRO) values ('TK0015','KT0016','koko@gm.com','123456','Khách thuê');
Insert into TAIKHOAN (MATK,MAKT,TENTAIKHOAN,MATKHAU,VAITRO) values ('TK0014','KT0015','lili@gm.com','123456','Khách thuê');
Insert into TAIKHOAN (MATK,MAKT,TENTAIKHOAN,MATKHAU,VAITRO) values ('TK0016','KT0017','k@gm.com','123456','Khách thuê');

--------------------------------------------------------
--  DDL for Index KHACHTHUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHACHTHUE_PK" ON "KHACHTHUE" ("MAKT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DICHVU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DICHVU_PK" ON "DICHVU" ("MADV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PHIEUDICHVU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PHIEUDICHVU_PK" ON "PHIEUDICHVU" ("MPDV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HOPDONG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOPDONG_PK" ON "HOPDONG" ("MHD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PHONG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PHONG_PK" ON "PHONG" ("MAP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KHACHNGANHAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHACHNGANHAN_PK" ON "KHACHNGANHAN" ("MAKT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HOADON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOADON_PK" ON "HOADON" ("MAHD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TAIKHOAN
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TAIKHOAN" ON "TAIKHOAN" ("MATK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CTHOPDONG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CTHOPDONG_PK" ON "CTHOPDONG" ("MHD", "MAKT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CTPDV_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CTPDV_PK" ON "CTPDV" ("MADV", "MPDV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CTHD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CTHD_PK" ON "CTHD" ("MAHD", "LOAIHD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_NGBD_NGKT_KHACHNGANHAN_KHACHTHUE_IN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_NGBD_NGKT_KHACHNGANHAN_KHACHTHUE_IN" BEFORE INSERT ON KHACHNGANHAN
FOR EACH ROW

DECLARE 
    v_NGAYBD KHACHTHUE.NGAYBATDAU%TYPE;
    v_NGAYKT KHACHTHUE.NGAYKETTHUC%TYPE;

BEGIN
    SELECT NGAYBATDAU, NGAYKETTHUC INTO v_NGAYBD, v_NGAYKT
    FROM KHACHTHUE
    WHERE KHACHTHUE.MAKT=:new.MADD;

    IF (v_NGAYBD > :new.NGAYBATDAU) THEN
        RAISE_APPLICATION_ERROR (-20005, 'Ng�y b?t �?u c?a kh�ch ng?n h?n ph?i l?n h�n ho?c b?ng ng�y b?t �?u c?a b?n');
    END IF;
        --Ki?m tra �i?u ki?n v_NGAYKT b� h�n ng�y b?t �?u c?a kh�ch ng?n h?n m?i th�m ho?c s?a Thị b�o l?i
    IF (v_NGAYKT < :new.NGAYKETTHUC) THEN
        RAISE_APPLICATION_ERROR (-20006, 'Ng�y k?t th�c c?a kh�ch ng?n h?n ph?i b� h�n ho?c ng�y k?t th�c c?a b?n');
    END IF;

END;
/
ALTER TRIGGER "TRG_NGBD_NGKT_KHACHNGANHAN_KHACHTHUE_IN" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_NGBD_NGKT_KHACHTHUE_KHACHNGANHAN_UP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_NGBD_NGKT_KHACHTHUE_KHACHNGANHAN_UP" 
BEFORE UPDATE OF NGAYBATDAU, NGAYKETTHUC ON KHACHTHUE
FOR EACH ROW

 --T?o bi?n v_NGAYBD, v_NGAYKT
DECLARE 
    v_NGAYBD KHACHNGANHAN.NGAYBATDAU%TYPE;
    v_NGAYKT KHACHNGANHAN.NGAYKETTHUC%TYPE;
BEGIN

    --T?m ng�y b?t �?u, ng�y k?t th�c c?a kh�ch ng?n h?n v� Lêu v�o bi?n v_NGAYBD, v_NGAYKT
    SELECT MIN(NGAYBATDAU), MAX(NGAYKETTHUC) INTO v_NGAYBD, v_NGAYKT
    FROM KHACHNGANHAN
    WHERE KHACHNGANHAN.MADD=:new.MAKT;     

    --Ki?m tra �i?u ki?n v_NGAYBD b� h�n ng�y b?t �?u c?a kh�ch �?i di?n m?i s?a Thị b�o l?i
    IF (v_NGAYBD < :new.NGAYBATDAU) THEN
        RAISE_APPLICATION_ERROR (-20003, 'Ng�y b?t �?u c?a kh�ch ph?i b� h�n ng�y b?t �?u c?a kh�ch ng?n h?n c?a kh�ch ��');
    END IF;
     --Ki?m tra �i?u ki?n v_NGAYKT l?n h�n ng�y k?t th�c c?a kh�ch �?i di?n m?i s?a Thị b�o l?i
    IF (v_NGAYKT > :new.NGAYKETTHUC) THEN
        RAISE_APPLICATION_ERROR (-20004, 'Ng�y k?t th�c c?a kh�ch ph?i l?n h�n ng�y k?t th�c c?a kh�ch ng?n h?n c?a kh�ch ��');
    END IF;

END;
/
ALTER TRIGGER "TRG_NGBD_NGKT_KHACHTHUE_KHACHNGANHAN_UP" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_NGKT_NGBD_KHACHTHUE_HOPDONG_UP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_NGKT_NGBD_KHACHTHUE_HOPDONG_UP" 
BEFORE UPDATE OF NGAYBATDAU, NGAYKETTHUC ON KHACHTHUE
FOR EACH ROW

DECLARE 
    --T?o bi?n v_NGAYKT, v_NGAYBD
    v_NGAYKT HOPDONG.NGAYKETTHUC%TYPE;
    v_NGAYBD HOPDONG.NGAYBATDAU%TYPE;

BEGIN

    --T?m ng�y k?t th�c, ng�y b?t �?u c?a h?p �?ng v� Lêu v�o bi?n v_NGAYKT, v_NGAYBD
    SELECT MAX(HOPDONG.NGAYKETTHUC), MIN(HOPDONG.NGAYBATDAU)
    INTO v_NGAYKT, v_NGAYBD
    FROM HOPDONG
    INNER JOIN CTHOPDONG ON HOPDONG.MHD = CTHOPDONG.MHD
    WHERE CTHOPDONG.MAKT = :new.MAKT ;

    --Ki?m tra �i?u ki?n Nữu v_NGAYKT b� h�n ng�y k?t th�c c?a Khách thuê sau khi s?a Thị b�o l?i
    IF (v_NGAYKT < :new.NGAYKETTHUC) THEN
        -- C?t b? ph?n m? l?i ORA- trong chu?i l?i
        RAISE_APPLICATION_ERROR(-20001, 'Ng�y k?t th�c c?a m?t Khách thuê ph?i b� h�n ho?c b?ng ng�y k?t th�c h?p �?ng c?a Khách thuê');
    END IF;

   --Ki?m tra �i?u ki?n Nữu v_NGAYBD l?n h�n ng�y b?t �?u c?a Khách thuê sau khi s?a Thị b�o l?i
    IF (v_NGAYBD > :new.NGAYBATDAU) THEN
        RAISE_APPLICATION_ERROR(-20002,'Ng�y b?t �?u c?a m?t Khách thuê ph?i l?n h�n ho?c b?ng ng�y b?t �?u c?a h?p �?ng c?a Khách thuê');
    END IF;
END;
/
ALTER TRIGGER "TRG_NGKT_NGBD_KHACHTHUE_HOPDONG_UP" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_THANGNAM_HOADON_IN_UP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_THANGNAM_HOADON_IN_UP" 
BEFORE INSERT OR UPDATE OF THANG, NAM ON HOADON
FOR EACH ROW

DECLARE   
    --T?o bi?n v_NGBD, v_THANGBD, v_NAMBD
    v_NGBD HOPDONG.NGAYBATDAU%TYPE;
    v_NGKT HOPDONG.NGAYKETTHUC%TYPE;
    v_THANGBD HOADON.THANG%TYPE;
    v_NAMBD HOADON.NAM%TYPE;
    v_THANGKT HOADON.THANG%TYPE;
    v_NAMKT HOADON.NAM%TYPE;

BEGIN

    --T?m ng�y b?t �?u c?a h?p �?ng Lêu v�o bi?n v_NGBD
    SELECT HOPDONG.NGAYBATDAU, HOPDONG.NGAYKETTHUC INTO v_NGBD, v_NGKT
    FROM HOPDONG,PHONG
    WHERE PHONG.MAP=HOPDONG.MAP AND PHONG.MAP=:new.MAP AND HOPDONG.TINHTRANG='Hiệu lực';

    --L?y th�ng v� n�m t? v_NGBD Lêu v�o v_THANGBD, v_NAMBD
    v_THANGBD := EXTRACT(MONTH FROM v_NGBD);
    v_NAMBD := EXTRACT(YEAR FROM v_NGBD);
    
    v_THANGKT := EXTRACT(MONTH FROM v_NGKT);
    v_NAMKT := EXTRACT(YEAR FROM v_NGKT);

    --Ki?m tra �i?u ki?n v_NAMBD l?n h�n n�m t?o ho?c s?a h�a ��n Thị b�o l?i
    IF (v_NAMBD>:new.NAM) THEN
            RAISE_APPLICATION_ERROR(-20007, 'N�m c?a h�a ��n ph?i l?n h�n ho?c b?ng n�m c?a h?p �?ng');
    
         --Ki?m tra �i?u ki?n Nữu v_NAMBD b?ng n�m t?o h�a ��n v� v_THANGBD l?n h�n th�ng t?o ho?c s?a h�a ��n Thị b�o l?i
     ELSIF    (v_NAMBD = :new.NAM AND v_THANGBD > :new.THANG) THEN
            RAISE_APPLICATION_ERROR(-20008, 'Th�ng c?a h�a ��n ph?i l?n h�n ho?c b?ng th�ng c?a h?p �?ng');
            
    ELSIF (v_NAMKT<:new.NAM) THEN
            RAISE_APPLICATION_ERROR(-20009, 'N�m c?a h�a ��n ph?i b� h�n ho?c b?ng n�m k?t th�c c?a h?p �?ng');
    ELSIF (V_NAMKT=:NEW.NAM AND v_THANGKT<:new.NAM) THEN
            RAISE_APPLICATION_ERROR(-20010, 'Th�ng c?a h�a ��n ph?i b� h�n ho?c b?ng th�ng k?t th�c c?a h?p �?ng');

    END IF;
END;
/
ALTER TRIGGER "TRG_THANGNAM_HOADON_IN_UP" ENABLE;
--------------------------------------------------------
--  DDL for Procedure PROC_GIA_HAN_HOP_DONG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROC_GIA_HAN_HOP_DONG" (
    p_mhd_cu hopdong.mhd%type,
    p_ngayketthuc_moi hopdong.ngayketthuc%type,
    p_madd_moi hopdong.madd%type,
    p_map_moi hopdong.map%type,
    p_tiencoc_moi hopdong.tiencoc%type
)
is
    v_ngayketthuc_cu date;

begin
    --Tim ngay ket thuc hop dong cu
    select ngayketthuc 
    into v_ngayketthuc_cu
    from hopdong
    where mhd = p_mhd_cu;
    --Huy hop dong cu
        UPDATE hopdong 
        SET tinhtrang = 'Hết hiệu lực'
        WHERE mhd = p_mhd_cu;

        -- C?p nh?t t?nh Trầng v� s? ng�?i trong Phòng
        UPDATE phong
        SET 
            trangthai = 'Còn Trống', 
            songuoi = 0
        WHERE map IN (
            SELECT map
            FROM hopdong
            WHERE mhd = p_mhd_cu
        );
    --Tao hop dong moi
    begin
      proc_them_hop_dong(v_ngayketthuc_cu, p_ngayketthuc_moi, p_tiencoc_moi, p_madd_moi, p_map_moi);
    end;
    commit;

    exception
    when others then
        rollback;
        dbms_output.put_line('�? x?y ra l?i!');
end;

/
--------------------------------------------------------
--  DDL for Procedure PROC_HOAN_TAT_HOP_DONG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROC_HOAN_TAT_HOP_DONG" (p_mhd hopdong.mhd%TYPE)
IS 
    v_ngaybatdau_hopdong DATE; v_ngayketthuc_hopdong DATE;
    v_map_hopdong VARCHAR2(100);v_songuoi_hopdong NUMBER;
BEGIN    
    UPDATE hopdong -- C?p nh?t t?nh Trầng h?p �?ng
    SET tinhtrang = 'Hiệu lực' WHERE mhd = p_mhd;
    SELECT ngaybatdau, ngayketthuc, map INTO v_ngaybatdau_hopdong, v_ngayketthuc_hopdong, v_map_hopdong -- T?m ng�y b?t �?u, ng�y k?t th�c, m? Phòng trong h?p �?ng
    FROM hopdong WHERE mhd = p_mhd;
    UPDATE khachthue  -- C?p nh?t ng�y b?t �?u c?a c�c Khách thuê trong h?p �?ng
    SET ngaybatdau = v_ngaybatdau_hopdong WHERE (khachthue.ngaybatdau IS NULL OR khachthue.ngaybatdau > v_ngaybatdau_hopdong)
    AND khachthue.makt IN (
        SELECT cthopdong.makt
        FROM cthopdong
        WHERE cthopdong.mhd = p_mhd);   
    UPDATE khachthue -- C?p nh?t ng�y k?t th�c c?a c�c Khách thuê trong h?p �?ng
    SET ngayketthuc = v_ngayketthuc_hopdong WHERE khachthue.makt IN (
        SELECT cthopdong.makt
        FROM cthopdong
        WHERE cthopdong.mhd = p_mhd) AND (khachthue.ngayketthuc IS NULL OR khachthue.ngayketthuc < v_ngayketthuc_hopdong);    
    UPDATE phong -- C?p nh?t t?nh Trầng c?a Phòng
    SET trangthai = 'Đã cho thuê'WHERE map = v_map_hopdong;   
    SELECT COUNT(*) -- T?m s? Lê?ng ng�?i trong h?p �?ng
    INTO v_songuoi_hopdong
    FROM cthopdong WHERE mhd = p_mhd;    
    UPDATE phong -- C?p nh?t s? Lê?ng ng�?i trong Phòng t��ng ?ng
    SET songuoi = v_songuoi_hopdong WHERE map = v_map_hopdong;
    COMMIT; DBMS_OUTPUT.PUT_LINE('Ho�n t?t h?p �?ng. M? h?p �?ng: ' || p_mhd);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK; DBMS_OUTPUT.PUT_LINE('�? x?y ra l?i!');
END;

/
--------------------------------------------------------
--  DDL for Procedure PROC_HUY_HOP_DONG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROC_HUY_HOP_DONG" (p_mhd hopdong.mhd%TYPE ) 
IS 
    CURSOR cur_makt IS SELECT makt FROM cthopdong WHERE mhd = p_mhd; 
    v_makt cthopdong.makt%TYPE; v_ngayketthuc_hopdong_trenhat DATE; 
BEGIN 
    UPDATE hopdong SET tinhtrang = 'Hết hiệu lực' WHERE mhd = p_mhd; -- C?p nh?t t?nh Trầng h?p �?ng
    UPDATE phong -- C?p nh?t t?nh Trầng v� s? ng�?i trong Phòng
    SET trangthai = 'Còn Trống',  songuoi = 0 WHERE map IN ( SELECT map FROM hopdong WHERE mhd = p_mhd ); 
    OPEN cur_makt; 
    LOOP 
        FETCH cur_makt INTO v_makt; 
        EXIT WHEN cur_makt%NOTFOUND; 
        SELECT MAX(hopdong.ngayketthuc) INTO v_ngayketthuc_hopdong_trenhat -- T?m ng�y k?t th�c h?p �?ng tr? nh?t c?a Khách thuê 
        FROM hopdong JOIN cthopdong ON cthopdong.mhd = hopdong.mhd JOIN khachthue ON khachthue.makt = cthopdong.makt  WHERE hopdong.tinhtrang = 'Hiệu lực'  
        AND cthopdong.makt = v_makt; 
        IF v_ngayketthuc_hopdong_trenhat IS NULL THEN  
            UPDATE khachthue -- C?p nh?t ng�y k?t th�c c?a c�c kh�ch trong cthopdong Lê ng�y hi?n t?i
            SET ngayketthuc = TRUNC(SYSDATE) WHERE khachthue.ngayketthuc > TRUNC(SYSDATE) AND khachthue.makt = v_makt; 
        ELSE  
            UPDATE khachthue  -- C?p nh?t ng�y k?t th�c c?a c�c kh�ch trong cthopdong Lê ng�y k?t th�c h?p �?ng tr? nh?t
            SET ngayketthuc = v_ngayketthuc_hopdong_trenhat WHERE khachthue.ngayketthuc > v_ngayketthuc_hopdong_trenhat AND khachthue.makt = v_makt; 
        END IF; 
    END LOOP; 
    CLOSE cur_makt; 
    COMMIT; 
    DBMS_OUTPUT.PUT_LINE('�? h?y h?p �?ng. M? h?p �?ng: ' || p_mhd); 
EXCEPTION 
    WHEN OTHERS THEN 
        ROLLBACK; DBMS_OUTPUT.PUT_LINE('�? x?y ra l?i!'); 
END;

/
--------------------------------------------------------
--  DDL for Procedure PROC_THEM_CHI_TIET_HOP_DONG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROC_THEM_CHI_TIET_HOP_DONG" (
    p_makt cthopdong.makt%type,
    p_mhd cthopdong.mhd%type
)
is
    v_ngayketthuc_kt date;
    v_ngayhientai date;

begin
    --Lay ngay ket thuc hop dong tuong ung
    SELECT to_date(trunc(sysdate), 'DD-MM-YYYY') into v_ngayhientai 
    FROM DUAL;

    --Tim ngay ket thuc cua khach thue tuong ung
    select ngayketthuc 
    into v_ngayketthuc_kt
    from khachthue
    where makt = p_makt;

     if (v_ngayketthuc_kt is null or  v_ngayketthuc_kt > v_ngayhientai) then
        insert into cthopdong (mhd, makt)
        values (p_mhd, p_makt);
        commit;
        dbms_output.put_line('�? th�m m? Khách thuê ' || p_makt || ' v�o h?p �?ng ' || p_mhd);
    else 
        commit;
        dbms_output.put_line('Kh�ch �? r?i kh?i Phòng. Th�m kh�ng th�nh c�ng!');
    end if;    
    exception
    when others then
        rollback;
        dbms_output.put_line('�? x?y ra l?i!');
end;

/
--------------------------------------------------------
--  DDL for Procedure PROC_THEM_HOP_DONG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROC_THEM_HOP_DONG" (
    p_ngaybatdau in hopdong.ngaybatdau%type, 
    p_ngayketthuc in hopdong.ngayketthuc%type,
    p_tiencoc in hopdong.tiencoc%type,
    p_madd in hopdong.madd%type,
    p_map in hopdong.map%type
)
is 
   v_mhd varchar2(100);
   v_giathue number;
begin
    -- Tao ma hop dong moi
    select 'HD' || lpad(nvl(to_number(substr(max(mhd), 3)), 0) + 1, 3, '0')
    into v_mhd
    from hopdong;

    -- Lay gia thue cua phong
    select gia 
    into v_giathue 
    from phong
    where phong.map = p_map;

    -- Them hop dong moi
    insert into hopdong (mhd, ngaybatdau, ngayketthuc, madd, map, giathue, tiencoc, tinhtrang)
    values (v_mhd, p_ngaybatdau, p_ngayketthuc, p_madd, p_map , v_giathue, p_tiencoc, 'Ch�a ho�n t?t'); 

    -- Them chi tiet hop dong moi
    insert into cthopdong (mhd, makt) 
    values (v_mhd, p_madd);

    commit;

    dbms_output.put_line('�? th�m h?p �?ng m?i. M? h?p �?ng: ' || v_mhd);
exception
    when others then
        rollback;
        dbms_output.put_line('�? x?y ra l?i!');
end;

/
--------------------------------------------------------
--  DDL for Procedure PROC_THEM_KHACH_NGAN_HAN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROC_THEM_KHACH_NGAN_HAN" (
    p_hoten khachnganhan.hoten%type,
    p_gioitinh khachnganhan.gioitinh%type,
    p_ngaysinh khachnganhan.ngaysinh%type,
    p_sdt IN VARCHAR2 DEFAULT NULL,
    p_cccd IN VARCHAR2 DEFAULT NULL,
    p_email IN VARCHAR2 DEFAULT NULL,
    p_madd khachnganhan.madd%type,
    p_ngaybatdau khachnganhan.ngaybatdau%type,
    p_ngayketthuc khachnganhan.ngayketthuc%type
)
IS
    v_ma_khachnganhan khachnganhan.makt%type;
    v_check_madd number;
BEGIN
    -- Ki?m tra xem madd c� t?n t?i trong b?ng KHACHTHUE kh�ng
    SELECT 'KNH' || LPAD(NVL(TO_NUMBER(SUBSTR(MAX(makt), 4)), 0) + 1, 3, '0')
    INTO v_ma_khachnganhan
    FROM khachnganhan; 

    -- Ki?m tra xem madd c� t?n t?i trong b?ng KHACHTHUE kh�ng
    SELECT count(*)
    INTO v_check_madd 
    FROM KHACHTHUE WHERE MAKT = p_madd;

    IF (v_check_madd = 0) THEN 
        DBMS_OUTPUT.PUT_LINE('Kh�ch �?i di?n thu� kh�ng h?p l?');
        -- Th�m rollback �? h?y b? thao t�c ch�n d? li?u Nữu madd kh�ng h?p l?
        ROLLBACK;
        -- K?t th�c procedure Nữu madd kh�ng h?p l?
        RETURN;
    END IF;

    -- Ch�n d? li?u m?i
    INSERT INTO khachnganhan (makt, hoten, gioitinh, ngaysinh, sdt, cccd, email, madd, trangthai, ngaybatdau, ngayketthuc) 
    VALUES (v_ma_khachnganhan, p_hoten, p_gioitinh, p_ngaysinh, p_sdt, p_cccd, p_email, p_madd, 'Chờ duyệt', p_ngaybatdau, p_ngayketthuc);

    -- COMMIT ��?c di chuy?n xu?ng d�?i �? �?m b?o r?ng ch? ��?c Thịc hi?n khi kh�ng c� l?i
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
    -- Nữu c� l?i, s? kh�ng Thịc hi?n ��?c ROLLBACK, do �� kh�ng c?n th�m ROLLBACK ? ��y
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20013, 'L?i khi ch�n d? li?u: ' || SQLERRM);

END;

/
--------------------------------------------------------
--  DDL for Procedure SUA_CTHD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SUA_CTHD" (
    P_MAHD IN HOADON.MAHD%TYPE,
    P_LOAIHD IN CTHD.LOAIHD%TYPE,
    P_SL IN CTHD.SL%TYPE,
    P_DONGIA IN CTHD.DONGIA%TYPE
    --P_THANHTIEN IN CTHD.THANHTIEN%TYPE
) AS
    v_OLD_THANHTIEN CTHD.THANHTIEN%TYPE;
    v_NEW_THANHTIEN CTHD.THANHTIEN%TYPE;
BEGIN
    -- L?y gi� tr? THANHTIEN c? c?a chi ti?t h�a ��n
    SELECT THANHTIEN INTO v_OLD_THANHTIEN
    FROM CTHD
    WHERE MAHD = P_MAHD AND LOAIHD = P_LOAIHD;
    
    -- T�nh to�n gi� tr? THANHTIEN m?i
    v_NEW_THANHTIEN := P_SL * P_DONGIA;
    
    -- C?p nh?t chi ti?t h�a ��n
    UPDATE CTHD SET SL = P_SL, DONGIA = P_DONGIA, THANHTIEN = v_NEW_THANHTIEN
    WHERE MAHD = P_MAHD AND LOAIHD = P_LOAIHD;
    
    -- C?p nh?t t?ng ti?n h�a ��n
    UPDATE HOADON
    SET TONGTIEN = TONGTIEN - v_OLD_THANHTIEN + v_NEW_THANHTIEN--, CONNO = TONGTIEN
    WHERE MAHD = P_MAHD;

    -- C?p nh?t c�ng Nữ trong h�a ��n
    UPDATE HOADON
    SET CONNO = CONNO - v_OLD_THANHTIEN + v_NEW_THANHTIEN
    WHERE MAHD = P_MAHD;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SUA_CTHD;

/
--------------------------------------------------------
--  DDL for Procedure SUA_DICHVU
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SUA_DICHVU" (
    p_dichvu_id dichvu.madv%type,
    p_dichvu_tendichvu dichvu.tendichvu%type
)
is 
    v_count number;
    v_count2 number;
begin
    select count(*) 
    into v_count
    from dichvu 
    where madv = p_dichvu_id;
    select count(*) 
    into v_count2
    from dichvu 
    where tendichvu = p_dichvu_tendichvu;

    if (v_count > 0) then 
        if (v_count2 = 0) then

            update dichvu
            set tendichvu = p_dichvu_tendichvu
            where madv = p_dichvu_id;
            commit; 
            dbms_output.put_line('C?p nh?t d?ch v? c� m? d?ch v?: ' || p_dichvu_id || ' th�nh c�ng!');
        else  
            dbms_output.put_line('T�n d?ch v? �? t?n t?i');
        end if;    
    else 

        dbms_output.put_line('M? d?ch v? kh�ng t?n t?i');
        commit;
    end if;
end;

/
--------------------------------------------------------
--  DDL for Procedure THEM_CTHD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "THEM_CTHD" (
    P_MAHD IN HOADON.MAHD%TYPE,
    P_LOAIHD IN CTHD.LOAIHD%TYPE,
    P_SL IN CTHD.SL%TYPE,
    P_DONGIA IN CTHD.DONGIA%TYPE
) AS
    V_THANHTIEN CTHD.THANHTIEN%TYPE;
BEGIN
    
 V_THANHTIEN := P_SL * P_DONGIA;


    INSERT INTO CTHD (MAHD, LOAIHD, SL, DONGIA, THANHTIEN)
    VALUES (P_MAHD, P_LOAIHD, P_SL, P_DONGIA,V_THANHTIEN);


    UPDATE HOADON
    SET TONGTIEN = TONGTIEN + V_THANHTIEN
    WHERE MAHD = P_MAHD;


    UPDATE HOADON
    SET CONNO = CONNO + V_THANHTIEN
    WHERE MAHD = P_MAHD;
END;

/
--------------------------------------------------------
--  DDL for Procedure THEM_DICHVU
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "THEM_DICHVU" (
    p_dichvu_ten dichvu.tendichvu%type
)
is 
    v_madv varchar2(100);
    v_count number;
begin 
    select count(*) 
    into v_count
    from dichvu 
    where tendichvu = p_dichvu_ten;
    if (v_count = 0) then 
    select 'DV' || lpad(nvl(to_number(substr(max(madv), 3)), 0) + 1, 3, '0')
    into v_madv
    from dichvu;


    insert into dichvu (madv, tendichvu) 
    values (v_madv, p_dichvu_ten);
    commit;
    else 
        dbms_output.put_line('T�n d?ch v? �? t?n t?i');
        commit;
    end if;


    dbms_output.put_line('�? th�m d?ch v? m?i. M? d?ch v?: ' || v_madv);
end;

/
--------------------------------------------------------
--  DDL for Procedure THEM_HOADON
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "THEM_HOADON" (
  p_thang IN NUMBER,
  p_nam IN NUMBER,
  p_map IN PHONG.MAP%TYPE
)
AS
  v_mahd VARCHAR2(6);
  v_tongtien NUMBER;
  v_conno NUMBER;
BEGIN

  SELECT 'HD' || LPAD(NVL(TO_NUMBER(SUBSTR(MAX(mahd), 3)), 0) + 1, 4, '0') INTO v_mahd
  FROM HOADON;

	  SELECT GIATHUE INTO v_tongtien FROM HOPDONG WHERE MAP = p_map AND TINHTRANG = 'Hiệu lực';

  v_conno := v_tongtien;

  INSERT INTO HOADON (mahd, map, thang, nam, tongtien, trangthai, conno)
  VALUES (v_mahd, p_map, p_thang, p_nam, 0 , 'Chưa thanh toán', v_conno);

  INSERT INTO CTHD (mahd, loaihd, sl, dongia, thanhtien)
  VALUES (v_mahd, 'Phòng', 1, v_tongtien, v_tongtien);

  UPDATE HOADON
  SET TONGTIEN= v_tongtien
  WHERE MAHD = v_mahd;

END them_HoaDon;

/
--------------------------------------------------------
--  DDL for Procedure THEMKHACHTHUE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "THEMKHACHTHUE" (
    p_Ten IN VARCHAR2,
    p_GioiTinh IN VARCHAR2,
    p_NgaySinh IN DATE,
    p_SDT IN VARCHAR2 DEFAULT NULL,
    p_CCCD IN VARCHAR2 DEFAULT NULL,
    P_Email IN VARCHAR2 DEFAULT NULL
)
IS
    v_MaKT CHAR(6);
    v_MaTK CHAR(6);
BEGIN
   SELECT 'KT' || LPAD(NVL(TO_NUMBER(SUBSTR(MAX(MAKT), 3)), 0) + 1, 4, '0') INTO v_MaKT
   FROM KHACHTHUE;
   
   SELECT 'TK' || LPAD(NVL(TO_NUMBER(SUBSTR(MAX(MATK), 3)), 0) + 1, 4, '0') INTO v_MaTK
   FROM TAIKHOAN;
    INSERT INTO KHACHTHUE (MAKT, HOTEN, GIOITINH, NGAYSINH, SDT, CCCD, EMAIL)
    VALUES (v_MaKT, p_Ten, p_GioiTinh, p_NgaySinh, p_SDT, p_CCCD, p_Email);
    if (P_Email IS NULL) then
    DBMS_OUTPUT.PUT_LINE('L?i');
    else
    INSERT INTO TAIKHOAN (MATK, MAKT, TENTAIKHOAN, MATKHAU, VAITRO) VALUES (v_MaTK,v_MaKT, p_Email, '123456', 'Khách thuê');

    end if;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('L?i: ' || SQLERRM);
END;

/
--------------------------------------------------------
--  DDL for Procedure THEMPHONG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "THEMPHONG" (
    p_TenPhong IN VARCHAR2,
    p_LoaiPhong IN VARCHAR2,
    p_DienTich IN NUMBER,
    p_GiaThue IN NUMBER
)
IS
    v_MaPhong CHAR(4);
BEGIN
   SELECT 'P' || LPAD(NVL(TO_NUMBER(SUBSTR(MAX(MAP), 3)), 0) + 1, 3, '0') INTO v_MaPhong
   FROM PHONG;
    INSERT INTO PHONG (MAP, TENPG, LOAI, SONGUOI, DIENTICH, TRANGTHAI, GIA)
    VALUES (v_MaPhong, p_TenPhong, p_LoaiPhong, 0, p_DienTich, 'Còn Trống', p_GiaThue);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('L?i: ' || SQLERRM);
END;

/
--------------------------------------------------------
--  DDL for Procedure XOA_CTHD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "XOA_CTHD" (
    P_MAHD IN HOADON.MAHD%TYPE,
    P_LOAIHD IN CTHD.LOAIHD%TYPE,
    P_SL IN CTHD.SL%TYPE,
    P_DONGIA IN CTHD.DONGIA%TYPE
) AS
    V_THANHTIEN CTHD.THANHTIEN%TYPE;
BEGIN

    SELECT THANHTIEN INTO V_THANHTIEN
    FROM CTHD
    WHERE MAHD = P_MAHD AND LOAIHD = P_LOAIHD AND SL = P_SL AND DONGIA = P_DONGIA;

    DELETE FROM CTHD
    WHERE MAHD = P_MAHD AND LOAIHD = P_LOAIHD AND SL = P_SL AND DONGIA = P_DONGIA;

    UPDATE HOADON
    SET TONGTIEN = TONGTIEN - V_THANHTIEN
    WHERE MAHD = P_MAHD;

    UPDATE HOADON
    SET CONNO = CONNO - V_THANHTIEN
    WHERE MAHD = P_MAHD;
END;

/
--------------------------------------------------------
--  DDL for Procedure XOA_DICHVU
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "XOA_DICHVU" (
    P_MADV IN DICHVU.MADV%TYPE
)
IS
    V_COUNT NUMBER;
    V_COUNT_1 NUMBER;
BEGIN

    SELECT COUNT(*) INTO V_COUNT FROM DICHVU WHERE MADV = P_MADV;

    IF V_COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20015, 'M? d?ch v? kh�ng t?n t?i.');
    END IF;
    SELECT COUNT(*) 
    INTO V_COUNT_1
    FROM CTPDV 
    WHERE MADV = P_MADV
    AND TINHTRANG = 'Chưa hoàn thành';

    IF (V_COUNT_1 = 0) THEN 
        DELETE FROM CTPDV WHERE MADV = P_MADV;
        DELETE FROM DICHVU WHERE MADV = P_MADV;
    ELSE 
        RAISE_APPLICATION_ERROR(-20002,'Kh�ng Thị x�a d?ch v? v? c?n �ang s? d?ng');
    END IF;

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('X�a d?ch v? th�nh c�ng!');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK; 
        RAISE; 
END XOA_DICHVU;

/
--------------------------------------------------------
--  DDL for Procedure XOA_HOADON
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "XOA_HOADON" (
    P_MAHD IN char
)
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM HOADON WHERE MAHD = P_MAHD;

    IF V_COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20012, 'M? h�a ��n kh�ng t?n t?i');
    END IF;

    DELETE FROM CTHD WHERE MAHD = P_MAHD;

    DELETE FROM HOADON WHERE MAHD = P_MAHD;

    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK; 
        RAISE; 
END XOA_HOADON;

/
--------------------------------------------------------
--  DDL for Procedure XOA_HOPDONG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "XOA_HOPDONG" (
  P_MHD CHAR
)
IS
  V_TRANGTHAI_HD VARCHAR2(20);
BEGIN
  SELECT TINHTRANG INTO V_TRANGTHAI_HD
  FROM HOPDONG
  WHERE MHD = P_MHD;

  IF V_TRANGTHAI_HD = 'Hiệu lực' THEN
    RAISE_APPLICATION_ERROR(-20011, 'H?p �?ng �ang ? Trầng th�i "Hiệu lực" n�n kh�ng x�a d�?c!');
  ELSE 
    DELETE FROM CTHOPDONG WHERE MHD = P_MHD;

    DELETE FROM HOPDONG WHERE MHD = P_MHD;
    END IF;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
        ROLLBACK; 
        RAISE;
END XOA_HOPDONG;

/
--------------------------------------------------------
--  DDL for Procedure XOA_KHACH
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "XOA_KHACH" (p_MAKT IN CHAR)
IS
  v_HOPDONG_COUNT NUMBER;
BEGIN
    v_HOPDONG_COUNT := 0;
  SELECT COUNT(*) INTO v_HOPDONG_COUNT
  FROM HOPDONG HD, CTHOPDONG CT
  WHERE CT.MAKT = p_MAKT AND TINHTRANG = 'Hiệu lực' AND HD.MHD = CT.MHD;

  IF (v_HOPDONG_COUNT = 0) THEN 

    DELETE FROM CTHOPDONG WHERE MAKT = p_MAKT;
    
    DELETE FROM CTHOPDONG WHERE MHD IN (SELECT MHD FROM HOPDONG WHERE MADD = p_MAKT);
    DELETE FROM HOPDONG WHERE MADD = p_MAKT;
    DELETE FROM TAIKHOAN WHERE MAKT = p_MAKT;
    DELETE FROM KHACHNGANHAN WHERE MADD = p_MAKT;
    DELETE FROM KHACHTHUE WHERE MAKT = p_MAKT;  
  END IF;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END XOA_KHACH;

/
--------------------------------------------------------
--  DDL for Procedure XOA_PHIEU_DICH_VU
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "XOA_PHIEU_DICH_VU" (
    P_MPDV IN PHIEUDICHVU.MPDV%TYPE
)
IS
    V_COUNT NUMBER;
    V_COUNT_1 NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM PHIEUDICHVU WHERE MPDV = P_MPDV;

    IF V_COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20013, 'M? phi?u d?ch v? kh�ng t?n t?i.');
    END IF;

    SELECT COUNT(*) 
    INTO V_COUNT_1
    FROM CTPDV 
    WHERE MPDV = P_MPDV
    AND TINHTRANG = 'Chưa hoàn thành';

    IF (V_COUNT_1 = 0) THEN 
        DELETE FROM CTPDV WHERE MPDV = P_MPDV; 
        DELETE FROM PHIEUDICHVU WHERE MPDV = P_MPDV;
    ELSE 
        RAISE_APPLICATION_ERROR(-20002,'Kh�ng Thị x�a d?ch v? v? c?n �ang s? d?ng');
    END IF;

    COMMIT; 

    DBMS_OUTPUT.PUT_LINE('X�a phi?u d?ch v? th�nh c�ng!');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK; 
        RAISE;
END XOA_PHIEU_DICH_VU;

/
--------------------------------------------------------
--  DDL for Procedure XOA_PHONG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "XOA_PHONG" (
  P_MAP CHAR
)
AS
  V_TRANGTHAI_PHONG VARCHAR2(20);
BEGIN

  SELECT TRANGTHAI INTO V_TRANGTHAI_PHONG
  FROM PHONG
  WHERE MAP = P_MAP;

  IF V_TRANGTHAI_PHONG != 'Còn Trống' THEN
    RAISE_APPLICATION_ERROR(-20014, 'Phòng ph?i Trầng th�i "Còn Trống" m?i x�a ��?c!');

  ELSE
  DELETE FROM HOPDONG WHERE MAP = P_MAP;

  DELETE FROM HOADON WHERE MAP = P_MAP;

  DELETE FROM PHIEUDICHVU WHERE MAP = P_MAP;

  DELETE FROM PHONG WHERE MAP = P_MAP;

  END IF;
  COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK; 
        RAISE;
END XOA_PHONG;

/
--------------------------------------------------------
--  DDL for Procedure XOA_TAIKHOANKHACH
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "XOA_TAIKHOANKHACH" (p_MAKT IN CHAR)
IS
  v_HOPDONG_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_HOPDONG_COUNT
  FROM HOPDONG HD, CTHOPDONG CT
  WHERE CT.MAKT = p_MAKT AND TINHTRANG = 'Hiệu lực' AND HD.MHD = CT.MHD;

  IF v_HOPDONG_COUNT = 0 THEN 

    DELETE FROM TAIKHOAN WHERE MAKT = p_MAKT;
    COMMIT;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END XOA_TAIKHOANKHACH;

/
--------------------------------------------------------
--  Constraints for Table KHACHTHUE
--------------------------------------------------------

  ALTER TABLE "KHACHTHUE" ADD CONSTRAINT "KHACHTHUE_PK" PRIMARY KEY ("MAKT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHACHTHUE" ADD CONSTRAINT "KHACHTHUE_NGAYBATDAU_CHECK" CHECK (NGAYBATDAU <NGAYKETTHUC) ENABLE;
  ALTER TABLE "KHACHTHUE" ADD CONSTRAINT "KHACHTHUE_GIOITINH" CHECK (gioitinh in ('Nam', 'Nữ')) ENABLE;
  ALTER TABLE "KHACHTHUE" ADD CONSTRAINT "KHACHTHUE_NGAYSINH_CHECK" CHECK (NGAYBATDAU > NGAYSINH) ENABLE;
--------------------------------------------------------
--  Constraints for Table PHONG
--------------------------------------------------------

  ALTER TABLE "PHONG" ADD CONSTRAINT "PHONG_PK" PRIMARY KEY ("MAP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PHONG" ADD CONSTRAINT "PHONG_TRANGTHAI" CHECK (trangthai in ('Còn Trống', 'Đã cho thuê')) ENABLE;
  ALTER TABLE "PHONG" ADD CONSTRAINT "PHONG_SONGUOI_VALUE" CHECK (songuoi >= 0) ENABLE;
  ALTER TABLE "PHONG" ADD CONSTRAINT "PHONG_DIENTICH_VALUE" CHECK (dientich > 0) ENABLE;
  ALTER TABLE "PHONG" ADD CONSTRAINT "PHONG_GIA_VALUE" CHECK (gia > 0) ENABLE;
--------------------------------------------------------
--  Constraints for Table KHACHNGANHAN
--------------------------------------------------------

  ALTER TABLE "KHACHNGANHAN" ADD CONSTRAINT "KHACHNGANHAN_PK" PRIMARY KEY ("MAKT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHACHNGANHAN" ADD CONSTRAINT "KHACHNGANHAN_NGAYSINH_CHECK" CHECK (NGAYBATDAU > NGAYSINH) ENABLE;
  ALTER TABLE "KHACHNGANHAN" ADD CONSTRAINT "KHACHNGANHAN_NGAYBATDAU_CHECK_1" CHECK (NGAYBATDAU < NGAYKETTHUC) ENABLE;
  ALTER TABLE "KHACHNGANHAN" ADD CONSTRAINT "KHACHNGANHAN_TRANGTHAI" CHECK (trangthai in ('Chờ duyệt','Đã duyệt')) ENABLE;
--------------------------------------------------------
--  Constraints for Table HOADON
--------------------------------------------------------

  ALTER TABLE "HOADON" MODIFY ("MAHD" NOT NULL ENABLE);
  ALTER TABLE "HOADON" ADD CONSTRAINT "HOADON_PK" PRIMARY KEY ("MAHD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HOADON" ADD CONSTRAINT "HOADON_TRANGTHAI" CHECK (trangthai in ('Đã thanh toán', 'Chưa thanh toán')) ENABLE;
  ALTER TABLE "HOADON" ADD CONSTRAINT "HOADON_TONGTIEN" CHECK (tongtien >= 0) ENABLE;
--------------------------------------------------------
--  Constraints for Table DICHVU
--------------------------------------------------------

  ALTER TABLE "DICHVU" ADD CONSTRAINT "DICHVU_PK" PRIMARY KEY ("MADV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PHIEUDICHVU
--------------------------------------------------------

  ALTER TABLE "PHIEUDICHVU" ADD CONSTRAINT "PHIEUDICHVU_PK" PRIMARY KEY ("MPDV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PHIEUDICHVU" ADD CONSTRAINT "PHIEUDICHVU_SOLUONGDV_VALUE" CHECK (soluongdv > 0) ENABLE;
--------------------------------------------------------
--  Constraints for Table HOPDONG
--------------------------------------------------------

  ALTER TABLE "HOPDONG" ADD CONSTRAINT "HOPDONG_PK" PRIMARY KEY ("MHD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HOPDONG" ADD CONSTRAINT "HOPDONG_NGAYBD_CHECK" CHECK (NGAYBATDAU < NGAYKETTHUC) ENABLE;
  ALTER TABLE "HOPDONG" ADD CONSTRAINT "HOPDONG_TRANGTHAI" CHECK (tinhtrang in ('Ch�a ho�n t?t', 'Hiệu lực', 'Hết hiệu lực')) ENABLE;
  ALTER TABLE "HOPDONG" ADD CONSTRAINT "HOPDONG_TIENCOC_VALUE" CHECK (tiencoc > 0) ENABLE;
--------------------------------------------------------
--  Constraints for Table CTHOPDONG
--------------------------------------------------------

  ALTER TABLE "CTHOPDONG" MODIFY ("MHD" NOT NULL ENABLE);
  ALTER TABLE "CTHOPDONG" MODIFY ("MAKT" NOT NULL ENABLE);
  ALTER TABLE "CTHOPDONG" ADD CONSTRAINT "CTHOPDONG_PK" PRIMARY KEY ("MHD", "MAKT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CTPDV
--------------------------------------------------------

  ALTER TABLE "CTPDV" ADD CONSTRAINT "CTPDV_TINHTRANG" CHECK (tinhtrang in ('Chưa hoàn thành', 'Ho�n th�nh')) ENABLE;
  ALTER TABLE "CTPDV" MODIFY ("MADV" NOT NULL ENABLE);
  ALTER TABLE "CTPDV" MODIFY ("MPDV" NOT NULL ENABLE);
  ALTER TABLE "CTPDV" ADD CONSTRAINT "CTPDV_PK" PRIMARY KEY ("MADV", "MPDV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAIKHOAN
--------------------------------------------------------

  ALTER TABLE "TAIKHOAN" ADD CONSTRAINT "PK_TAIKHOAN" PRIMARY KEY ("MATK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CTHD
--------------------------------------------------------

  ALTER TABLE "CTHD" MODIFY ("MAHD" NOT NULL ENABLE);
  ALTER TABLE "CTHD" ADD CONSTRAINT "CTHD_LOAIHD" CHECK (loaihd in ('Phòng','Điện','Nước')) ENABLE;
  ALTER TABLE "CTHD" ADD CONSTRAINT "CTHD_SL_VALUE" CHECK (sl > 0) ENABLE;
  ALTER TABLE "CTHD" ADD CONSTRAINT "CTHD_DONGIA_VALUE" CHECK (dongia > 0) ENABLE;
  ALTER TABLE "CTHD" ADD CONSTRAINT "CTHD_THANHTIEN_VALUE" CHECK (thanhtien > 0) ENABLE;
  ALTER TABLE "CTHD" MODIFY ("LOAIHD" NOT NULL ENABLE);
  ALTER TABLE "CTHD" ADD CONSTRAINT "CTHD_PK" PRIMARY KEY ("MAHD", "LOAIHD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CTHD
--------------------------------------------------------

  ALTER TABLE "CTHD" ADD CONSTRAINT "CTHD_MAHD_FK" FOREIGN KEY ("MAHD")
	  REFERENCES "HOADON" ("MAHD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CTHOPDONG
--------------------------------------------------------

  ALTER TABLE "CTHOPDONG" ADD CONSTRAINT "CTHDONG_MHD_FK" FOREIGN KEY ("MHD")
	  REFERENCES "HOPDONG" ("MHD") ENABLE;
  ALTER TABLE "CTHOPDONG" ADD CONSTRAINT "CTHDONG_MKT_FK" FOREIGN KEY ("MAKT")
	  REFERENCES "KHACHTHUE" ("MAKT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CTPDV
--------------------------------------------------------

  ALTER TABLE "CTPDV" ADD CONSTRAINT "CTPDV_MPDV_FK" FOREIGN KEY ("MPDV")
	  REFERENCES "PHIEUDICHVU" ("MPDV") ENABLE;
  ALTER TABLE "CTPDV" ADD CONSTRAINT "CTPDV_MADV_FK" FOREIGN KEY ("MADV")
	  REFERENCES "DICHVU" ("MADV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOADON
--------------------------------------------------------

  ALTER TABLE "HOADON" ADD CONSTRAINT "HOADON_MAP_FK" FOREIGN KEY ("MAP")
	  REFERENCES "PHONG" ("MAP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOPDONG
--------------------------------------------------------

  ALTER TABLE "HOPDONG" ADD CONSTRAINT "HDONG_MAP_FK" FOREIGN KEY ("MAP")
	  REFERENCES "PHONG" ("MAP") ENABLE;
  ALTER TABLE "HOPDONG" ADD CONSTRAINT "HDONG_MADD_FK" FOREIGN KEY ("MADD")
	  REFERENCES "KHACHTHUE" ("MAKT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KHACHNGANHAN
--------------------------------------------------------

  ALTER TABLE "KHACHNGANHAN" ADD CONSTRAINT "KHACHNGANHAN_MDD_FK" FOREIGN KEY ("MADD")
	  REFERENCES "KHACHTHUE" ("MAKT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHIEUDICHVU
--------------------------------------------------------

  ALTER TABLE "PHIEUDICHVU" ADD CONSTRAINT "PDV_MAP_FK" FOREIGN KEY ("MAP")
	  REFERENCES "PHONG" ("MAP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAIKHOAN
--------------------------------------------------------

  ALTER TABLE "TAIKHOAN" ADD CONSTRAINT "TAIKHOAN_MAKT_FK" FOREIGN KEY ("MAKT")
	  REFERENCES "KHACHTHUE" ("MAKT") ENABLE;
